name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "mobile", "extension", "small fix", "important"]
assignees:
  - Mateusz
body:
  - type: markdown
    attributes:
      value: |
        A clear and concise description of what the bug is
  - type: input
    id: find
    attributes:
      label: where to find
      description: If applicable, add screenshots/video to help explain your problem. Remember to mark the area in the application thats impacted.
      placeholder: 
  - type: input
    id: priority
    attributes:
      label: Priority
      description: What is the impact of this bug on the user, how critical is to fix? P0, P1 .. P4 [Reference - Google Issue tracker priority levels](https://developers.google.com/issue-tracker/concepts/issues#priority)
      placeholder: 
    validations:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Chrome)
        - 1.0.3 (Edge)
        - 0.3.5 (Firefox)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Mobile IOS
        - Mobile Android
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: attachments
    attributes:
      label: Screenshots/Video
      description: If applicable, add screenshots/video to help explain your problem. Remember to mark the area in the application thats impacted.
      placeholder: 
      
  

